# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Visual Journalist | Brian Williamson’s portfolio site for design, graphics, illustrations and videos
description: > # this means to ignore newlines until "baseurl:"
  BRIAN WILLIAMSON is a graphic artist, interactive developer and designer for Voice of America. He designs, illustrates, animates and writes code to tell stories. VOA provides objective news and information in 45 languages to over 235 million people around the world every week. For 75 years, VOA has broadcast content that many people cannot get locally: objective news and information about the US, their region and the world.
title_short: Visual Journalist | Brian Williamson’s portfolio | 
description_short: > # this means to ignore newlines until "baseurl:"
  Brian Williamson is a graphic artist, interactive developer and designer for VOA. He designs, illustrates, animates and writes code to tell stories.

description_link: > # 
  BRIAN WILLIAMSON is a graphic artist, interactive developer and designer for Voice of America. He designs, illustrates, animates and writes code to tell stories. VOA provides objective news and information in 45 languages to over 235 million people around the world every week. For 75 years, VOA has broadcast content that many people cannot get locally: objective news and information about the US, their region and the world.

categories_list:
  - name: interactive
    totalStories: 3
    description: BRIAN WILLIAMSON started as a newspaper page designer at the St. Louis Post-Dispatch, designing everything from the front page to business and feature pages. At some point he transitioned to designing interactive content for the newspaper. He is comfortable working with HTML, CSS, JavaScript, Node, JSON and creating data visualizations with D3 and Leaflet.
  - name: design
    totalStories: 4
    description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  - name: comics
    totalStories: 3
    description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  - name: illustration
    totalStories: 4
    description: BRIAN WILLIAMSON creates conceptual illustrations, portraits, infographics and comics. He's illustrated everything from abstract stories on the economy to practical how-to stories on exercise. His illustrations have been featured in newspapers around the country. He is equally comfortable working with dirty, real-world paint and the virtual equivalent. 
  - name: video
    totalStories: 4
    description: BRIAN WILLIAMSON creates short videos to tell stories, help introduce new tools, promote new projects and provide project retrospectives. He can shoots and edits short interviews, write a script, storyboard it, and produce the final video.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # http://projects.voanews.com/circumvention #localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: "@BrianWmson"
github_username: "bbgvisualjournalist"

development_mode: true
development_warning: This site is currently under active development. There is a lot of lorem ipsum.

test_var: <h2>this is a <a href="https://google.com/">test</a></h2>

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock


permalink: /:categories/:title